a=float(input("Enter student's marks"))
b=float(input(""))
c=float(input(""))
d=float(input(""))
e=float(input(""))
f=float(input("Enter Total marks"))
p1=a*f/100
p2=b*f/100
p3=c*f/100
p4=d*f/100
p5=d*f/100
Total_percentage=(a+b+c+d+e)*5f/100
